### ISSUE TITLE
Problem while running on OSX

### ISSUE THREAD

**Issue by amanpsbhatia** [stormspirit/libtachyon#4]
Hi,

I am running this on OSX. I am able to compile code but the test cases are not working. The error I am getting is  **java.lang.UnsupportedClassVersionError.**.

I tried using version 1.8 and 1.7 separately, but I am getting the same error. The complete stack trace is as follows :
**Message: Could not create enum for MASTER_HOSTNAME of class alluxio/Constants
From Java: java.lang.UnsupportedClassVersionError: alluxio/Constants : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)**

In JNIHelper.cc, on line 680, a version argument is set while creating the VM. Here the existing version was JNI_VERSION_1_2. But for java 6 onwards, this should be JNI_VERSION_1_6. I modified that as I am using java 1.8.
Although, when I deleted java 1.6 (default version used by Mac), I am getting  the following error :
**No Java runtime present, requesting install.**
This is coming even though I have a JRE corresponding to 1.8 installed. I am able to run normal java programs.

On further investigation, I found that there is some problem with jdk on mac. It seems to be a bug where JNI explicitly looks for the default java.
https://bugs.openjdk.java.net/browse/JDK-7131356.

There is something similar reported here :
https://github.com/s-u/rJava/issues/37

Any probable solution for this?

Thanks,

**Comment by ryanphuang** [comment]
As a workaround, I temporarily set the ldflags to directly linking against libjvm instead of using `-framework JavaVM`, which will load the old version (1.6) libjvm regardless of the current java env settings. You'll need to set the `LD_LIBRARY_PATH ` as explained in the wiki (e.g., to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/server`).

Will find a better fix when I have time.

**Comment by amanpsbhatia** [comment]
Hi,
I did the above mentioned changes, but still I am getting the same error on running the test cases.
**No Java runtime present, requesting install.**

**Comment by ryanphuang** [comment]
I think you need to install the legacy Java 6 runtime https://support.apple.com/kb/DL1572?locale=en_US.
